### PR TITLE
EP-784 POST expects body with Status param specified (tested)

### PR DESCRIPTION
**Pull request by milos-expend**

### CODE REVIEW

**Comment by HJEGeorge** [comment]
This isn't the correct solution. It's brittle and adds to our technical debt. Why not try to alleviate some of that debt by fast-forwarding this branch to upstream master, and then testing the syncing locally? Otherwise a more suitable fix would be to find where the methods are mapped and change it there, or simply change the call in our backend to be `xeropayments.post(status="DELETED")` (not sure whether there is a client somewhere or not).

**Comment by milos-expend** [comment]
@HJEGeorge its correct given following criteria:

1) we want to avoid updating whole repo from upstream (that requires testing and might possibly break our code in subtle ways we might only find out in PROD)
2) if its not broken dont fix it. everything works for us at the moment ... even if clear that the client we are using is not complitely up-to-date, subset of functionality we need is there

@rvangraan what do you think? should i fetch all updates from freakboy3742/pyxero and see if payment deletion works? I am closer to what i have basically done ... patching missing functionality and everything else works (so dont touch it)

**Comment by HJEGeorge** [comment]
If we're too scared to do something that eliviates technical debt because
we can't test it, it means we should make our testing and development
environment better, not avoid doing it altogether.

**Comment by milos-expend** [comment]
i got busy fixing xero currency issues ... please @HJEGeorge if you want pyxero updated add it to this ticket or open new issue ... and we shall act on it.

in the mean time ... i still want to commit this quick&dirty fix to resolve my current issues. Sometimes you just do that kinda fixup ... even if dirty. my 0.02

**Comment by milos-expend** [comment]
image
@HJEGeorge basically your suggestion to use POST will not work out of the box, POST does not add payment UID to /v2/Payments base URL ... POSTs straight to it.

**Comment by milos-expend** [comment]
image
was checking freakboy3742/pyxero dont think he supports POST version of API ... funny since last commit is only 6 months ago, so dont scream "abandonware" in your face.

**Comment by milos-expend** [comment]
@HJEGeorge @rvangraan please we need to reach consensus on this :) ... pulling upstream will not fix our issues since code also uses DELETE (checked). Adding a tweak in POST handler to insert UID for Payments amounts to about same kind of trickery i am doing by re-routing delete request to POST for Payments. Let me know whats your suggestion. I still want to merge this as it is since it fixes our problem and does not introduce any new ones.

**Review by HJEGeorge — APPROVED** [review]
Have created Technical Debt ticket [EP-1522](https://curoodev.atlassian.net/browse/EP-1522). The solution may be to migrate to `XeroAPI/xero-python` for full accounting API support, but this is a larger task, as we would need to move over our sync-uid code.

**Pull request merged**
